server:
  port: 9001

spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8837,127.0.0.1:8848,127.0.0.1:8859
      config:
        server-addr: 127.0.0.1:8837,127.0.0.1:8848,127.0.0.1:8859
        file-extension: yaml





